### ISSUE TITLE
AttributeError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: undefined symbol: omp_VERSION

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1032]
```
pythran --version
Traceback (most recent call last):
  File "/home/pierre/.pyenv/versions/3.6.6/bin/pythran", line 11, in <module>
    load_entry_point('pythran', 'console_scripts', 'pythran')()
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pierre/Dev/pythran/pythran/__init__.py", line 40, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx, Python
  File "/home/pierre/Dev/pythran/pythran/backend.py", line 8, in <module>
    from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
  File "/home/pierre/Dev/pythran/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/home/pierre/Dev/pythran/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/home/pierre/Dev/pythran/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/home/pierre/Dev/pythran/pythran/tables.py", line 4487, in <module>
    omp_version = omp.VERSION
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/site-packages/omp/__init__.py", line 68, in __getattr__
    return getattr(self.libomp, 'omp_' + name)
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/pierre/.pyenv/versions/3.6.6/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: undefined symbol: omp_VERSION
```

A quick fix is of course to change `except ImportError:` to `except (ImportError, AttributeError):` in https://github.com/serge-sans-paille/pythran/blob/master/pythran/tables.py#L4488

**Comment by serge-sans-paille** [comment]
Your fix looks correct, feel free to propose a patch!

**Comment by serge-sans-paille** [comment]
Thanks for the patch o/
