### ISSUE TITLE
pip install fails with 'ascii' codec issue

### ISSUE THREAD

**Issue by apatlpo** [serge-sans-paille/pythran#1130]
On linux, here is how it looks like:

```
(fluidsim) datahome/aponte% pip download pythran
Collecting pythran
  Downloading https://files.pythonhosted.org/packages/82/de/3a0afb468aa3d3a8a46f43d9619e7d620ae88103cef90e718e3d888863b5/pythran-0.9.0.tar.gz (6.7MB)
    100% |################################| 6.8MB 1.3MB/s
  Saved ./pythran-0.9.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-download-vrog1g4o/pythran/setup.py", line 174, in <module>
        long_description=longdescr("README.rst"),
      File "/tmp/pip-download-vrog1g4o/pythran/setup.py", line 165, in longdescr
        lines = list(readme)
      File "/home1/datahome/aponte/.miniconda3/envs/fluidsim/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-download-vrog1g4o/pythran/
```

Any idea where this is coming from?

Do you believe this [post](https://stackoverflow.com/questions/46046752/python-3-unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-0) may solve the issue ?

**Comment by apatlpo** [comment]
Adjusting the environment prior to running the pip install fixes the issue:
```
setenv LC_ALL en_US.UTF-8
```

**Comment by danFromTelAviv** [comment]
I had to use 

 `export LC_ALL='c.UTF-8'`
