### ISSUE TITLE
randint: IndexError in pythran/transformations/remove_named_arguments.py

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1309]
```
import numpy as np

# pythran export func()

def func():
    return np.random.randint(2, size=32)
```

gives

```
Traceback (most recent call last):
  File "/home/pierre/.pyenv/versions/3.7.2/bin/pythran", line 11, in <module>
    load_entry_point('pythran', 'console_scripts', 'pythran')()
  File "/home/pierre/Dev/pythran/pythran/run.py", line 165, in run
    **compile_flags(args))
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 470, in compile_pythranfile
    **kwargs)
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 393, in compile_pythrancode
    module_dir)
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 142, in generate_cxx
    optimizations, module_dir)
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 110, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/pierre/Dev/pythran/pythran/middlend.py", line 43, in refine
    pm.apply(RemoveNamedArguments, node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 230, in apply
    res = a.apply(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 193, in apply
    new_node = self.run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 185, in run
    n = super(Transformation, self).run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 326, in generic_visit
    new_node = self.visit(old_value)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/home/pierre/Dev/pythran/pythran/transformations/remove_named_arguments.py", line 89, in visit_Call
    replacements = self.handle_keywords(func_alias, node)
  File "/home/pierre/Dev/pythran/pythran/transformations/remove_named_arguments.py", line 61, in handle_keywords
    replacements[index] = deepcopy(defaults[index - nargs])
IndexError: list index out of range
```

**Comment by paugier** [comment]
I confirm that it solves the problem. Thank you Lucky Luke!

CC @rorroiga
