### ISSUE TITLE
Simple Boolean Concatenate gives Error

### ISSUE THREAD

**Issue by rorroiga** [serge-sans-paille/pythran#1311]
import numpy as np

#pythran export outputCodeActiveZoneOpt()
def outputCodeActiveZoneOpt():
    C3 = np.concatenate([np.array([True]),np.array([True])])
    return C3

gives

```
Traceback (most recent call last):
  File "/home/igajadua/.local/bin/pythran", line 10, in <module>
    sys.exit(run())
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/run.py", line 165, in run
    **compile_flags(args))
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/toolchain.py", line 472, in compile_pythranfile
    **kwargs)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/toolchain.py", line 395, in compile_pythrancode
    module_dir)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/toolchain.py", line 142, in generate_cxx
    optimizations, module_dir)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/toolchain.py", line 110, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/middlend.py", line 55, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 230, in apply
    res = a.apply(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 193, in apply
    new_node = self.run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 185, in run
    n = super(Transformation, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 121, in run
    super(Analysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 142, in run
    return super(ModuleAnalysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 121, in run
    super(Analysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/pure_expressions.py", line 71, in prepare
    super(PureExpressions, self).prepare(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/argument_effects.py", line 76, in run
    result = super(ArgumentEffects, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 142, in run
    return super(ModuleAnalysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 121, in run
    super(Analysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/argument_effects.py", line 69, in prepare
    super(ArgumentEffects, self).prepare(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 142, in run
    return super(ModuleAnalysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 121, in run
    super(Analysis, self).run(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/aliases.py", line 551, in visit_FunctionDef
    self.generic_visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/aliases.py", line 260, in visit_Return
    ret_aliases = self.visit(node.value)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/aliases.py", line 357, in visit_Call
    self.generic_visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/sw/freetools/python_anaconda/5.2.0/rh60_64/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/aliases.py", line 386, in visit_Attribute
    return self.add(node, {Aliases.access_path(node)})
  File "/home/igajadua/.local/lib/python3.6/site-packages/pythran/analyses/aliases.py", line 111, in access_path
    return Aliases.access_path(node.value)[demangle(node.attr)]
KeyError: 'bool'
```

**Comment by serge-sans-paille** [comment]
Thanks for reporting, #1312 should fix this, it has been merged into master.

**Comment by rorroiga** [comment]
Thank you Serge, it resolves the problem, but I found  another case where it has problems.

I will post it in another issue.

Regards,
Rodrigo Iga.
