### ISSUE TITLE
only in OSX and Python 3.7: AssertionError: Bad argument number for arguments: 6, expecting 7 

### ISSUE THREAD

**Issue by martibosch** [serge-sans-paille/pythran#1363]
Hello,
I am trying to update conda-forge to the latest release (v1.10) of PyLandStats. The [build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=72722&view=logs) succeeds in Linux (Python 3.6 and 3.7) and OSX with Python 3.6, but fails with OSX and Python 3.7. 

The issue is seemingly about the gast package. I leave the traceback below (the whole logs are available [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=72722&view=logs&jobId=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&taskId=0a2070c1-8027-59fc-ddea-6aec050600c1&lineStart=154&lineEnd=195&colStart=1&colEnd=174)):

```bash
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from pythran.dist import PythranExtension
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/__init__.py", line 40, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx, Python
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/backend.py", line 8, in <module>
    from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/tables.py", line 173, in <module>
    BINARY_UFUNC = {"accumulate": FunctionIntr()}
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/intrinsic.py", line 94, in __init__
    super(FunctionIntr, self).__init__(**kwargs)
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/pythran/intrinsic.py", line 58, in __init__
    [to_ast(d) for d in kwargs.get('defaults', [])])
  File "/usr/local/miniconda/conda-bld/pylandstats_1568711886754/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7/site-packages/gast/gast.py", line 19, in create_node
    format(Name, nbparam, len(Fields))
AssertionError: Bad argument number for arguments: 6, expecting 7
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1491, in build
    cwd=src_dir, stats=build_stats)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/usr/local/miniconda/conda-bld/pylandstats_1568711886754/work/conda_build.sh']' returned non-zero exit status 1.
```

Thank you in advance.
Martí

**Comment by serge-sans-paille** [comment]
The pythran version it's using is 0.9.3.post0, while it should be 0.9.3post1, let me check that.

**Comment by serge-sans-paille** [comment]
0.9.3post1 is available on conda-forge, and it indeed freezes gast/beniget dependencies to gast==0.2.2
beniget==0.1.0

**Comment by martibosch** [comment]
Hello.
Thank you again for your help. 
[I have updated](https://github.com/conda-forge/pylandstats-feedstock/pull/6/commits/33353dc453890541291b818b391b4ab4cc165524) the conda recipe so that pythran 0.9.3.post1 is required, nevertheless, [the build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=73131) fails due to the following:

```bash
Package python conflicts for:
pythran[version='>=0.9.3.post1'] -> beniget=0.1.0 -> python[version='2.7.*|3.6.*|>=3.5']
pip -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
wheel -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pythran[version='>=0.9.3.post1'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0']
setuptools[version='>=40.8.0'] -> certifi[version='>=2016.09'] -> python[version='2.7.*|3.6.*']
python=3.7
setuptools[version='>=40.8.0'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
```

How should I proceed?
Thanks in advance.
Martí

**Comment by serge-sans-paille** [comment]
This is beyond my field :-/ I'm as puzzled as you are by the fact osx build fails while the linux one is OK, esp. as we don't have anything os-specific in our recipes for OSX.

**Comment by paugier** [comment]
The `<3.7.0a0` for pythran is weird... I wonder from where this comes from.

**Comment by martibosch** [comment]
The automated pipelines did multiple unsuccessful attempts to resolve the dependency tree, until a TimeoutError was raised. The latest conflicts were:

```bash
Package python conflicts for:
pythran[version='>=0.9.3.post1'] -> networkx[version='>=2'] -> python[version='2.7.*|3.6.*|>=3.5']
pythran[version='>=0.9.3.post1'] -> networkx[version='>=2'] -> setuptools -> certifi[version='>=2016.09'] -> python[version='3.4.*|3.5.*|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0']
setuptools[version='>=40.8.0'] -> certifi[version='>=2016.09'] -> python[version='2.7.*|3.6.*']
setuptools[version='>=40.8.0'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
python=3.7
pythran[version='>=0.9.3.post1'] -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0']
wheel -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
pip -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0'].  Trying again in 81 seconds
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/upload_package", line 11, in <module>
    sys.exit(upload_package())
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_forge_ci_setup/build_utils.py", line 141, in upload_package
    retry_upload_or_check(recipe_root, owner, channel, [config_file])
  File "/usr/local/miniconda/lib/python3.7/site-packages/conda_forge_ci_setup/upload_or_check_non_existence.py", line 162, in retry_upload_or_check
    raise TimeoutError("Did not manage to upload package.  Failing.")
TimeoutError: Did not manage to upload package.  Failing.
```

I suspect that the line:

```bash
setuptools[version='>=40.8.0'] -> certifi[version='>=2016.09'] -> python[version='2.7.*|3.6.*']
```

is beyond this error since it does not feature Python 3.7. But this is in no case related to Pythran, so feel free to close it. I raised [another issue](https://github.com/regro/cf-scripts/issues/610) in conda-forge's dependency graph tracker. In any case, thank you for your help.

Martí

**Comment by serge-sans-paille** [comment]
ok, closing the issue then; Thanks a lot for tracking that down, it really helps to have downstream users like you o/
