### ISSUE TITLE
site.cfg conflicts with other uses

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1387]
Unfortunately, I am already using a file called 'site.cfg' for other purposes.  It would be good to either:
1. choose a different (more specific) name for pythran
2. A command line option or config option to specify a different name

**Comment by serge-sans-paille** [comment]
which file are you talking about? there's no `site.cfg` in the git tree...

**Comment by nbecker** [comment]
If I have a file called site.cfg in the directory:

```
 pythran _uvazel.py 
Traceback (most recent call last):
  File "/home/nbecker/.local/bin/pythran", line 10, in <module>
    sys.exit(run())
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/run.py", line 177, in run
    **compile_flags(args))
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/toolchain.py", line 480, in compile_pythranfile
    **kwargs)
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/toolchain.py", line 423, in compile_pythrancode
    **kwargs)
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/toolchain.py", line 366, in compile_cxxcode
    output_binary, **kwargs)
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/toolchain.py", line 310, in compile_cxxfile
    **kwargs)
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/dist.py", line 110, in __init__
    cfg_ext = cfg.make_extension(python=True, **kwargs)
  File "/home/nbecker/.local/lib/python3.7/site-packages/pythran/config.py", line 203, in make_extension
    numpy_blas = numpy_sys.get_info(user_blas)
  File "/home/nbecker/.local/lib/python3.7/site-packages/numpy/distutils/system_info.py", line 446, in get_info
    return cl().get_info(notfound_action)
  File "/home/nbecker/.local/lib/python3.7/site-packages/numpy/distutils/system_info.py", line 558, in __init__
    self.parse_config_files()
  File "/home/nbecker/.local/lib/python3.7/site-packages/numpy/distutils/system_info.py", line 566, in parse_config_files
    self.cp.read(self.files)
  File "/usr/lib64/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/lib64/python3.7/configparser.py", line 1079, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/nbecker/multibeam/site.cfg', line: 1
'import os\n'
```

**Comment by serge-sans-paille** [comment]
Site.cfg is used by distuils, this is independent from pythran, I can't do anything here. Looks like your usage in multibeam is incompatible with that :-/
