### ISSUE TITLE
Compile issue under windows with clang-cl

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1487]
Hi, 

I'm encountering an issue when compiling under windows (I'd rather just use Linux, but some users want windows) using clang-cl. I'm not quite sure if this is a pythran or a boost issue (I've found some references to this for boost). Here is the compile error, I'm still trying to wiggle down the code to a minimal example. 
```
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.so' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.dylib' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.so' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.dylib' [-Wunknown-argument]
clang-cl: error: no input files
In file included from C:\Users\jschrod\AppData\Local\Temp\tmp0xz7tcm4.cpp:62:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\pythonic/__builtin__/str/__mod__.hpp:9:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/format.hpp:38:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/format/internals.hpp:21:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/optional.hpp:15:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/optional/optional.hpp:47:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/type_traits/is_nothrow_move_assignable.hpp:15:
c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/type_traits/has_trivial_move_assign.hpp(49,4): error: no
      template named 'is_assignable'; did you mean 'std::is_assignable'?
   BOOST_HAS_TRIVIAL_MOVE_ASSIGN(T)
   ^
c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/type_traits/intrinsics.hpp(233,86): note: expanded from macro
      'BOOST_HAS_TRIVIAL_MOVE_ASSIGN'
#     define BOOST_HAS_TRIVIAL_MOVE_ASSIGN(T) (__is_trivially_assignable(T&, T&&) && is_assignable<T&, T&&>::val...
                                                                                     ^
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\type_traits(663,8): note:
      'std::is_assignable' declared here
struct is_assignable : bool_constant<__is_assignable(_To, _From)> {}; // determine whether _From can be assigned to _To
       ^
In file included from C:\Users\jschrod\AppData\Local\Temp\tmp0xz7tcm4.cpp:62:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\pythonic/__builtin__/str/__mod__.hpp:9:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/format.hpp:38:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/format/internals.hpp:21:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/optional.hpp:15:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/optional/optional.hpp:47:
In file included from c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/type_traits/is_nothrow_move_assignable.hpp:15:
c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/type_traits/has_trivial_move_assign.hpp(49,4): error: no
      template named 'is_volatile' in namespace 'boost'; did you mean 'std::is_volatile'?
   BOOST_HAS_TRIVIAL_MOVE_ASSIGN(T)
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
c:\users\jschrod\anaconda3\lib\site-packages/pythran\boost/type_traits/intrinsics.hpp(233,120): note: expanded from
      macro 'BOOST_HAS_TRIVIAL_MOVE_ASSIGN'
  ...(__is_trivially_assignable(T&, T&&) && is_assignable<T&, T&&>::value && !::boost::is_volatile<T>::value)
                                                                              ^~~~~~~~~
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include\type_traits(505,8): note:
      'std::is_volatile' declared here
struct is_volatile : bool_constant<is_volatile_v<_Ty>> {};
       ^
2 errors generated.
WARNING: Compilation error, trying hard to find its origin...
Traceback (most recent call last):
  File "c:\users\jschrod\anaconda3\lib\distutils\_msvccompiler.py", line 424, in compile
    self.spawn(args)
  File "c:\users\jschrod\anaconda3\lib\distutils\_msvccompiler.py", line 543, in spawn
    return super().spawn(cmd)
  File "c:\users\jschrod\anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 92, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "c:\users\jschrod\anaconda3\lib\site-packages\numpy\distutils\ccompiler.py", line 172, in CCompiler_spawn
    (cmd, s, msg))
distutils.errors.DistutilsExecError: Command "C:\Program Files\LLVM\bin\clang-cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_OPENBLAS -Ic:\users\jschrod\anaconda3\lib\site-packages/pythran -Ic:\users\jschrod\anaconda3\lib\site-packages\numpy\core\include -Ic:\users\jschrod\anaconda3\lib\site-packages\pythran_openblas\include\openblas -Ic:\users\jschrod\anaconda3\include -Ic:\users\jschrod\anaconda3\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /EHsc /TpC:\Users\jschrod\AppData\Local\Temp\tmp0xz7tcm4.cpp /FoC:\Users\jschrod\AppData\Local\Temp\tmpfs2ga1uu\Release\Users\jschrod\AppData\Local\Temp\tmp0xz7tcm4.obj /w" failed with exit status 1

During handling of the above exception, another exception occurred:
...
```

This seems to have been discussed in a boost github issue [here](https://github.com/boostorg/type_traits/issues/126), which says it is fixed in boost-1.7.0 (what version is pythran using?)

**Comment by cycomanic** [comment]
OK I just saw that pythran is using boost-1.6.8 would it be possible to move to 1.70?

**Comment by cycomanic** [comment]
OK some further follow up. The fix is trivial actually (and I just tested it to work) see [here](https://github.com/boostorg/type_traits/commit/ad326841ecca3e1a31102d5ddaf4e82f55a13742) 
not sure if it warrants upgrading boost, but it would be good if it could be fixed in pythran.

**Comment by serge-sans-paille** [comment]
pythran is already tested with a more recent version of boost through fedora, so I'll just upgrade the boost version. Thanks for the detailed report!
