### ISSUE TITLE
Exception raised during `pythran -h`

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1504]
With master:
```
pythran --help
Traceback (most recent call last):
  File "/home/pierre/.pyenv/versions/3.7.2/bin/pythran", line 11, in <module>
    load_entry_point('pythran', 'console_scripts', 'pythran')()
  File "/home/pierre/Dev/pythran/pythran/run.py", line 126, in run
    args, extra = parser.parse_known_args(sys.argv[1:])
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 1037, in __call__
    parser.print_help()
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 2474, in print_help
    self._print_message(self.format_help(), file)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 2458, in format_help
    return formatter.format_help()
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 525, in _format_action
    help_text = self._expand_help(action)
  File "/home/pierre/.pyenv/versions/3.7.2/lib/python3.7/argparse.py", line 614, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character '{' (0x7b) at index 32
```

**Comment by serge-sans-paille** [comment]
What a shame! As usual, when something in not tested, it tends to break.
