### ISSUE TITLE
run pythran error

### ISSUE THREAD

**Issue by guangpec1** [serge-sans-paille/pythran#1533]
Traceback (most recent call last):
  File "/usr/bin/pythran", line 11, in <module>
    load_entry_point('pythran==0.9.0', 'console_scripts', 'pythran')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2291, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/__init__.py", line 40, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx, Python
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/backend.py", line 8, in <module>
    from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/tables.py", line 173, in <module>
    BINARY_UFUNC = {"accumulate": FunctionIntr()}
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/intrinsic.py", line 94, in __init__
    super(FunctionIntr, self).__init__(**kwargs)
  File "/usr/lib/python2.7/site-packages/pythran-0.9.0-py2.7.egg/pythran/intrinsic.py", line 58, in __init__
    [to_ast(d) for d in kwargs.get('defaults', [])])
  File "build/bdist.linux-x86_64/egg/gast/gast.py", line 19, in create_node
AssertionError: Bad argument number for arguments: 6, expecting 7

**Comment by serge-sans-paille** [comment]
That's generally the result of an obsolete gast dependency. Can you `pip -U gast` and try again?

**Comment by guangpec1** [comment]
thanks,  I update the gast version  to gast-0.3.1 （pythran require is >= 0.3.0） ，the problem still exist.

**Comment by serge-sans-paille** [comment]
And I see that your pythran version is relatively old too, can you try to update it?

**Comment by guangpec1** [comment]
install a earlist version , another problem is following，thanks
  File "/usr/bin/pythran", line 11, in <module>
    load_entry_point('pythran==0.9.5', 'console_scripts', 'pythran')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 561, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2631, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2291, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2297, in resolve
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/__init__.py", line 40, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx, Python
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/backend.py", line 7, in <module>
    from pythran.analyses import LocalNodeDeclarations, GlobalDeclarations, Scope
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/analyses/aliases.py", line 6, in <module>
    from pythran.syntax import PythranSyntaxError
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/syntax.py", line 7, in <module>
    from pythran.tables import MODULES
  File "/usr/lib/python2.7/site-packages/pythran-0.9.5-py2.7.egg/pythran/tables.py", line 4, in <module>
    from inspect import getfullargspec

**Comment by guangpec1** [comment]
my sysytem is redhat

**Comment by serge-sans-paille** [comment]
can you provide the full backtrace? Note that using python3 would be much easier :-)

**Comment by guangpec1** [comment]
this problem root cause is python version, change python version from 2.7 to 3.6 , the problem is resolved ，thanks a lot
