### ISSUE TITLE
Unhelpful error message on tuple times float constant

### ISSUE THREAD

**Issue by DWesl** [serge-sans-paille/pythran#1554]
This file:
```python
# ~*~ coding: utf8 ~*~
import numpy as np

HOURS_PER_DAY = 24.
DAYS_PER_FORTNIGHT = 14.

#pythran export d0_dm0_a0_fit_np(float64[2], float64[])
def d0_dm0_a0_fit_np(parameters, tdata):
    resid_coef = parameters[0],
    resid_timescale = parameters[1],

    exp = np.exp
    return (resid_coef * exp(-tdata / (resid_timescale * DAYS_PER_FORTNIGHT)))
```
fails to compile with error message
```
$ pythran pythran_test.py
Traceback (most recent call last):
  File "/usr/bin/pythran", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3.7/site-packages/pythran/run.py", line 177, in run
    **compile_flags(args))
  File "/usr/lib/python3.7/site-packages/pythran/toolchain.py", line 490, in compile_pythranfile
    **kwargs)
  File "/usr/lib/python3.7/site-packages/pythran/toolchain.py", line 413, in compile_pythrancode
    module_dir)
  File "/usr/lib/python3.7/site-packages/pythran/toolchain.py", line 157, in generate_cxx
    entry_points=entry_points)
  File "/usr/lib/python3.7/site-packages/pythran/toolchain.py", line 120, in front_middle_end
    refine(pm, ir, optimizations)
  File "/usr/lib/python3.7/site-packages/pythran/middlend.py", line 57, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 235, in apply
    return a.apply(node)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 198, in apply
    new_node = self.run(node)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 186, in run
    n = super(Transformation, self).run(node)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 326, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 326, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 335, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/pythran/optimizations/constant_folding.py", line 184, in visit_BinOp
    node = self.generic_visit(node)
  File "/usr/lib/python3.7/ast.py", line 335, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/ast.py", line 326, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/pythran/optimizations/constant_folding.py", line 184, in visit_BinOp
    node = self.generic_visit(node)
  File "/usr/lib/python3.7/ast.py", line 335, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.7/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/usr/lib/python3.7/site-packages/pythran/optimizations/constant_folding.py", line 188, in visit_BinOp
    for _ in range(node.right.value)
TypeError: 'float' object cannot be interpreted as an integer
```

I eventually figured out it was due to the trailing commas on the parameter assignments, which caused `resid_timescale * DAYS_PER_FORTNIGHT` to be interpreted as `tuple * float`, which doesn't work.

I have no idea where in pythran would be the proper place to tag the syntax error, although I suppose an `assert` just before line 188 would work for most cases.  A try/except block around line 188 would also be an option.

**Comment by DWesl** [comment]
Looks good, thank you.
