### ISSUE TITLE
Regression: RuntimeError in analyses/range_values.py 

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1556]
```
import numpy as np

# pythran export strfunc_from_pdf(int32[:], float64[:, :], float64[:, :], float64, bool)

def strfunc_from_pdf(rxs, pdf, values, order, absolute):
    S_order = np.empty(rxs.shape)
    if absolute:
        values = abs(values)
    for irx in range(rxs.size):
        deltainc = abs((values[(irx, 1)] - values[(irx, 0)]))
        S_order[irx] = deltainc * np.sum((pdf[irx] * (values[irx] ** order)))
    return S_order
```
can be compiled by Pythran 0.9.5 but not with master. Without the `if absolute:`, no bug.

```
Traceback (most recent call last):
  File "/home/pierre/.pyenv/versions/3.8.2/bin/pythran", line 11, in <module>
    load_entry_point('pythran', 'console_scripts', 'pythran')()
  File "/home/pierre/Dev/pythran/pythran/run.py", line 175, in run
    pythran.compile_pythranfile(args.input_file,
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 471, in compile_pythranfile
    output_file = compile_pythrancode(module_name, open(file_path).read(),
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 394, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 138, in generate_cxx
    pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
  File "/home/pierre/Dev/pythran/pythran/toolchain.py", line 105, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/pierre/Dev/pythran/pythran/middlend.py", line 59, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 236, in apply
    return a.apply(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 199, in apply
    new_node = self.run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 187, in run
    n = super(Transformation, self).run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 143, in run
    return super(ModuleAnalysis, self).run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 122, in run
    super(Analysis, self).run(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/ast.py", line 360, in visit
    return visitor(node)
  File "/home/pierre/Dev/pythran/pythran/analyses/range_values.py", line 831, in generic_visit
    super(RangeValues, self).generic_visit(node)
  File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/ast.py", line 368, in generic_visit
    self.visit(item)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/ast.py", line 360, in visit
    return visitor(node)
  File "/home/pierre/Dev/pythran/pythran/analyses/range_values.py", line 495, in visit_FunctionDef
    self.function_visitor(node)
  File "/home/pierre/Dev/pythran/pythran/analyses/range_values.py", line 866, in function_visitor
    self.cfg_visit(next(self.cfg.successors(node)))
  File "/home/pierre/Dev/pythran/pythran/analyses/range_values.py", line 843, in cfg_visit
    nexts = self.visit(successor)
  File "/home/pierre/Dev/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/pierre/.pyenv/versions/3.8.2/lib/python3.8/ast.py", line 360, in visit
    return visitor(node)
  File "/home/pierre/Dev/pythran/pythran/analyses/range_values.py", line 1180, in visit_If
    for successor in successors:
RuntimeError: dictionary keys changed during iteration
```

**Comment by serge-sans-paille** [comment]
I don't reproduce with master... 

```console
% git rev-parse HEAD
521afc8848c95ad6eba15c5b0b258c9ced3a3a55
```

**Comment by serge-sans-paille** [comment]
beniget: 0.2.1
gast: 0.3.3

**Comment by paugier** [comment]
Actually, I get this bug only with Python 3.8...

**Comment by serge-sans-paille** [comment]
Then I can reproduce, thanks o/
