### ISSUE TITLE
AttributeError related to ast on python 2.7

### ISSUE THREAD

**Issue by jdemerss** [serge-sans-paille/pythran#1666]
Hi,

I would like to use pythran on python 2.7 
Howerver when I try to execute a test cas (with the dprod function)  I got this error :
 ```
>>> pythran mon_module.py
Traceback (most recent call last):
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\jdemersseman\Anaconda3\envs\python_2.7\Scripts\pythran.exe\__main__.py", line 7, in <module>
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\run.py", line 177, in run
    **compile_flags(args))
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\toolchain.py", line 479, in compile_pythranfile
    **kwargs)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\toolchain.py", line 402, in compile_pythrancode
    module_dir)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\toolchain.py", line 153, in generate_cxx
    entry_points=entry_points)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\toolchain.py", line 116, in front_middle_end
    refine(pm, ir, optimizations)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\middlend.py", line 23, in refine
    pm.apply(NormalizeTuples, node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 235, in apply
    return a.apply(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 198, in apply
    new_node = self.run(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 186, in run
    n = super(Transformation, self).run(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 96, in run
    return self.visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 297, in generic_visit
    value = self.visit(value)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\transformations\normalize_tuples.py", line 196, in visit_FunctionDef
    return self.generic_visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 297, in generic_visit
    value = self.visit(value)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 306, in generic_visit
    new_node = self.visit(old_value)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 297, in generic_visit
    value = self.visit(value)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\transformations\normalize_tuples.py", line 115, in visit_GeneratorExp
    return self.visit_AnyComp(node, 'elt')
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\transformations\normalize_tuples.py", line 98, in visit_AnyComp
    nnode = ConvertToTuple(gtarget, g[1]).visit(nnode)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 306, in generic_visit
    new_node = self.visit(old_value)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 306, in generic_visit
    new_node = self.visit(old_value)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\ast.py", line 241, in visit
    return visitor(node)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\transformations\normalize_tuples.py", line 25, in visit_Name
    ast.Name(self.tuple_id, ast.Load(), None, None)
  File "c:\users\jdemersseman\anaconda3\envs\python_2.7\lib\site-packages\pythran\transformations\normalize_tuples.py", line 22, in <lambda>
    ast.Index(ast.Constant(y, None)),
AttributeError: 'module' object has no attribute 'Index'

```

I have just done a `pip install pythran==0.9.5`.
I have the same error whether it is on Linux or Windows and  with or without virtual environment.

Is the correct way to install pythran for python 2.7 ?

**Comment by serge-sans-paille** [comment]
You should probably also bind the gast and beinget version

probably (untested)
gast==0.3.3
beniget==0.2.2

**Comment by jdemerss** [comment]
thanks that solved my issue. I can now start the compilation.

**Comment by serge-sans-paille** [comment]
Happy to help!
