### ISSUE TITLE
KeyError: <gast.gast.Num object... when declaring function with default arguments

### ISSUE THREAD

**Issue by yohplala** [serge-sans-paille/pythran#1720]
Hi,
I am sorry, I raise a ticket for this, maybe this is not appropriate. Please, just tell me.

First, I have installed pythran by use of anaconda.
Its version is not quite clear. Here is what tells me `pip freeze | grep pythran`
```
pythran @ file:///home/conda/feedstock_root/build_artifacts/pythran_1608037658665/work
```

Ok, so I have this error message when trying to compile this python script with `pythran min_max_pythran.py`.
I can confirm that this script works with python (it extracts min and max as stated by the docstring :)).

Any idea what could be wrong?
Thanks for your help.
Bests,

<details>

```python
import operator as op
import numpy as np
#from collections import deque

#pythran export min_max(float[], float)
def min_max(data: np.ndarray, threshold: float) -> np.ndarray:
    return 1
```

</details>

**Comment by jeanlaroche** [comment]
I don't think pythran supports type hits for the return `->` but I may be wrong. My version of pythran crashes when using this construct.

**Comment by yohplala** [comment]
> I don't think pythran supports type hits for the return `->` but I may be wrong. My version of pythran crashes when using this construct.

Hi Jean,
Thanks for your help.
Alas, even removing it, it seems pythran goes abit further, but ends up with a new ocurence of the same error.
Possibly I am using too much 'python tricks'.

<details>

```bash
(base) C:\Users\pierre\Documents\code\peaks>pythran min_max_pythran.py
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.so' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.dylib' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.so' [-Wunknown-argument]
clang-cl: error: no input files
clang-cl: warning: unknown argument ignored in clang-cl: '-print-file-name=libgomp.dylib' [-Wunknown-argument]
clang-cl: error: no input files
Traceback (most recent call last):
  File "C:\Users\pierre\Documents\Programs\Anaconda\Scripts\pythran-script.py", line 10, in <module>
    sys.exit(run())
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\run.py", line 179, in run
    **compile_flags(args))
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\toolchain.py", line 476, in compile_pythranfile
    **kwargs)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\toolchain.py", line 395, in compile_pythrancode
    module_dir)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\toolchain.py", line 140, in generate_cxx
    entry_points=entry_points)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\toolchain.py", line 105, in front_middle_end
    refine(pm, ir, optimizations)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\middlend.py", line 27, in refine
    pm.apply(ExpandBuiltins, node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 236, in apply
    return a.apply(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 199, in apply
    new_node = self.run(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 187, in run
    n = super(Transformation, self).run(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 96, in run
    return self.visit(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 262, in visit
    return visitor(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 317, in generic_visit
    value = self.visit(value)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 262, in visit
    return visitor(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 326, in generic_visit
    new_node = self.visit(old_value)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 262, in visit
    return visitor(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 326, in generic_visit
    new_node = self.visit(old_value)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\ast.py", line 262, in visit
    return visitor(node)
  File "C:\Users\pierre\Documents\Programs\Anaconda\lib\site-packages\pythran\transformations\expand_builtins.py", line 39, in visit_Name
    s not in self.locals[node] and
KeyError: <gast.gast.Name object at 0x000002B282144848>
```

</details>

**Comment by jeanlaroche** [comment]
This looks like a bug to me, pythran should not crash, ever. You should open a bug.

**Comment by serge-sans-paille** [comment]
Minimal reproducer:

```python
import operator as op
import numpy as np
#from collections import deque

#pythran export min_max(float[], float)
def min_max(data: np.ndarray, threshold: float) -> np.ndarray:

    return 1
```

basically removing type annotation solves the issue. This bug is enough for me to track this down, thanks!
