### ISSUE TITLE
pythran error after numpy update to 1.20 

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1731]
It seems like some of my code stops compiling since my system has updated to numpy-1.20. I've narrowed it down to the following code:
```python
import numpy as np

#pythran export apply_filter(complex128[:,:], complex128[:,:])
def apply_filter(E, wx):
    pols = E.shape[0]
    Ntaps = wx.shape[1]
    Xest = E.dtype.type(0)
    for k in range(pols):
        for i in range(Ntaps):
            Xest += E[k, i]*np.conj(wx[k,i])
    return Xest      
```

which fails with:
```
Traceback (most recent call last):
  File "/home/jschrod/.virtualenvs/pythran_pocketfft/bin/pythran", line 33, in <module>
    sys.exit(load_entry_point('pythran', 'console_scripts', 'pythran')())
  File "/home/jschrod/PycharmProjects/pythran/pythran/run.py", line 176, in run
    pythran.compile_pythranfile(args.input_file,
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 472, in compile_pythranfile
    output_file = compile_pythrancode(module_name, open(file_path).read(),
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 394, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 138, in generate_cxx
    pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 105, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/jschrod/PycharmProjects/pythran/pythran/middlend.py", line 61, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 236, in apply
    return a.apply(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 199, in apply
    new_node = self.run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 187, in run
    n = super(Transformation, self).run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 122, in run
    super(Analysis, self).run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib64/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib64/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib64/python3.8/ast.py", line 381, in generic_visit
    self.visit(value)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/analyses/potential_iterator.py", line 33, in visit_Call
    if all(isReadOnce(alias, i) for alias in self.aliases[node.func]):
  File "/home/jschrod/PycharmProjects/pythran/pythran/analyses/potential_iterator.py", line 33, in <genexpr>
    if all(isReadOnce(alias, i) for alias in self.aliases[node.func]):
  File "/home/jschrod/PycharmProjects/pythran/pythran/analyses/potential_iterator.py", line 32, in isReadOnce
    self.argument_read_once[f][i] <= 1)
IndexError: list index out of range
```

Some more cutting it down seems to point to the `E.dtype.type(0) code. 
The following fails:
```python
import numpy as np

#pythran export test(complex128)
def apply_filter(E):
    Xest = E.dtype.type(0)
    return Xest 
```

Error:
```python
Traceback (most recent call last):
  File "/home/jschrod/.virtualenvs/pythran_pocketfft/bin/pythran", line 33, in <module>
    sys.exit(load_entry_point('pythran', 'console_scripts', 'pythran')())
  File "/home/jschrod/PycharmProjects/pythran/pythran/run.py", line 176, in run
    pythran.compile_pythranfile(args.input_file,
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 472, in compile_pythranfile
    output_file = compile_pythrancode(module_name, open(file_path).read(),
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 394, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 138, in generate_cxx
    pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
  File "/home/jschrod/PycharmProjects/pythran/pythran/toolchain.py", line 105, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/jschrod/PycharmProjects/pythran/pythran/middlend.py", line 61, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 236, in apply
    return a.apply(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 199, in apply
    new_node = self.run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 187, in run
    n = super(Transformation, self).run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 95, in run
    self.prepare(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 90, in prepare
    result = d.run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 143, in run
    return super(ModuleAnalysis, self).run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 122, in run
    super(Analysis, self).run(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/analyses/range_values.py", line 833, in generic_visit
    super(RangeValues, self).generic_visit(node)
  File "/usr/lib64/python3.8/ast.py", line 379, in generic_visit
    self.visit(item)
  File "/home/jschrod/PycharmProjects/pythran/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/jschrod/PycharmProjects/pythran/pythran/analyses/range_values.py", line 836, in generic_visit
    if node in self.cfg:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by serge-sans-paille** [comment]
On Fri, Feb 26, 2021 at 12:47:53PM -0800, Jochen Schröder wrote:
> It seems like some of my code stops compiling since my system has updated to
> numpy-1.20. I've narrowed it down to the following code:

This is fixed in master

**Comment by cycomanic** [comment]
I still get the same error even on latest master.

**Comment by cycomanic** [comment]
Never mind, I had not cleared the build directory. Closing.
