### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by certik** [serge-sans-paille/pythran#1924]
I tried with pythran 0.10.0 from conda-forge on Apple M1:
```python
def myf(a, b):
    c = 0
    for i in range(100):
        c = (c + a)*b
    return c

def main():
    print(myf(3, 4))
```
and got:
```console
$ pythran a.py
WARNING:root:No pythran specification, nothing will be exported
Traceback (most recent call last):
  File "/Users/certik/miniforge3/envs/pythran/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/run.py", line 176, in run
    pythran.compile_pythranfile(args.input_file,
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/toolchain.py", line 473, in compile_pythranfile
    output_file = compile_pythrancode(module_name, fd.read(),
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/toolchain.py", line 394, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/toolchain.py", line 143, in generate_cxx
    content = pm.dump(Cxx, ir)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/passmanager.py", line 226, in dump
    return b.run(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/passmanager.py", line 143, in run
    return super(ModuleAnalysis, self).run(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/passmanager.py", line 122, in run
    super(Analysis, self).run(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 1324, in visit_Module
    decls_n_defns = list(filter(None, (self.visit(stmt) for stmt in
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 1324, in <genexpr>
    decls_n_defns = list(filter(None, (self.visit(stmt) for stmt in
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 1335, in visit_FunctionDef
    return visitor.visit(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 232, in visit
    return super(CxxFunction, self).visit(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 346, in visit_FunctionDef
    result_type.generate(ctx),
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 327, in generate
    self.of.generate(ctx))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in generate
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in <listcomp>
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 519, in <genexpr>
    texprs = (ctx(expr) for expr in self.exprs)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 129, in __call__
    t = node.generate(self)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in generate
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in <listcomp>
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 519, in <genexpr>
    texprs = (ctx(expr) for expr in self.exprs)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 129, in __call__
    t = node.generate(self)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in generate
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in <listcomp>
    *["std::declval<{0}>()".format(t) for t in texprs]))
...
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in generate
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 521, in <listcomp>
    *["std::declval<{0}>()".format(t) for t in texprs]))
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/cxxtypes.py", line 519, in <genexpr>
    texprs = (ctx(expr) for expr in self.exprs)
  File "/Users/certik/miniforge3/envs/pythran/lib/python3.10/site-packages/pythran/backend.py", line 129, in __call__
    t = node.generate(self)            
RecursionError: maximum recursion depth exceeded
```

**Comment by certik** [comment]
Thanks for fixing it. I tested the latest master and indeed this error is fixed. I discovered another related issue here: #1929.
