### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by certik** [serge-sans-paille/pythran#1930]
On Linux and Pythran 0.10.0:
```python
def triad(a: f32[:], b: f32[:], scalar: f32, c: f32[:]):
    N: i32
    i: i32
    N = size(a)
    for i in range(N): # type: parallel
        c[i] = a[i] + scalar * b[i]

def main():
    a: f32[10000]
    b: f32[10000]
    c: f32[10000]
    scalar: f32
    i: i32
    nsize: i32
    scalar = 10
    nsize = size(a)
    for i in range(nsize): # type: parallel
        a[i] = 5
        b[i] = 5
    triad(a, b, scalar, c)
    print("End Stream Triad")
```
and:
```console
$ pythran doconcurrentloop_01.py 
WARNING:root:No pythran specification, nothing will be exported
Traceback (most recent call last):
  File "/home/certik/miniconda3/envs/pythran/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/run.py", line 176, in run
    pythran.compile_pythranfile(args.input_file,
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/toolchain.py", line 473, in compile_pythranfile
    output_file = compile_pythrancode(module_name, fd.read(),
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/toolchain.py", line 394, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/toolchain.py", line 138, in generate_cxx
    pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/toolchain.py", line 105, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/middlend.py", line 33, in refine
    pm.apply(NormalizeStaticIf, node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 237, in apply
    return a.apply(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 200, in apply
    new_node = self.run(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 188, in run
    n = super(Transformation, self).run(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/transformations/normalize_static_if.py", line 130, in visit_Module
    self.generic_visit(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/ast.py", line 447, in generic_visit
    value = self.visit(value)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/transformations/normalize_static_if.py", line 180, in visit_FunctionDef
    self.cfgs.append(self.gather(CFG, node))
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 101, in gather
    return a.run(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 164, in run
    return super(FunctionAnalysis, self).run(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 122, in run
    super(Analysis, self).run(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/home/certik/miniconda3/envs/pythran/lib/python3.8/site-packages/pythran/analyses/cfg.py", line 51, in visit_FunctionDef
    currs, _ = self.visit(n)
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by serge-sans-paille** [comment]
If you try to compile this code with the `master` branch of Pythran, you will get a bunch of nice erros like

```
triad.py:1:13 error: Unbound identifier f32
----
def triad(a: f32[:], b: f32[:], scalar: f32, c: f32[:]):
             ^~~~ (o_0)
----
```

But the following will work like a charm:

```
import numpy as np

def triad(a, b, scalar, c):
    N = len(a)
    for i in range(N): # type: parallel
        c[i] = a[i] + scalar * b[i]

def main():
    a = np.empty(10000, dtype=np.float32)
    b = np.empty(10000, dtype=np.float32)
    c = np.empty(10000, dtype=np.float32)
    scalar = 10
    nsize = len(a)
    for i in range(nsize): # type: parallel
        a[i] = 5
        b[i] = 5
    triad(a, b, scalar, c)
    print("End Stream Triad")
```

I'm not aware of the `f32[1000]` syntax nor the `size` function. Do you have pointers to documentation on those? Thanks!

**Comment by certik** [comment]
> I'm not aware of the f32[1000] syntax nor the size function. Do you have pointers to documentation on those? Thanks!

That was my own syntax, I just forgot to remove it when trying pythran, but since I got the stacktrace, I reported it. I think this is now fixed in master. Thanks!
