### ISSUE TITLE
Compiling example for matmul returns `AssertionError: Bad argument number for Assign: 3, expecting 2`

### ISSUE THREAD

**Issue by ljmartin** [serge-sans-paille/pythran#2026]
Hi pythran, thank you for this project. 

I'm having trouble compiling the [matrix multiplication example from the manual](https://pythran.readthedocs.io/en/latest/MANUAL.html#first-steps). Oddly, the `dprod.py` example prior to that works fine, so I believe the install is working (install was via mamba so I don't have a setup.py). 

Do you have any idea what's leading to this error? 
Thanks! 

Here's the exact file:
```python
#pythran export matrix_multiply(float list list, float list list)
def zero(n,m): return [[0]*n for col in range(m)]
def matrix_multiply(m0, m1):
    new_matrix = zero(len(m0),len(m1[0]))
    for i in range(len(m0)):
        for j in range(len(m1[0])):
            for k in range(len(m1)):
                new_matrix[i][j] += m0[i][k]*m1[k][j]
    return new_matrix
```

and the big traceback from executing `pythran mm.py`:
```python
Traceback (most recent call last):
  File "/Users/ljmartin/miniconda3/envs/compchem/bin/pythran", line 11, in <module>
    sys.exit(run())
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/run.py", line 176, in run
    pythran.compile_pythranfile(args.input_file,
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/toolchain.py", line 473, in compile_pythranfile
    output_file = compile_pythrancode(module_name, fd.read(),
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/toolchain.py", line 394, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts,
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/toolchain.py", line 138, in generate_cxx
    pm, ir, docstrings = front_middle_end(module_name, code, optimizations,
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/toolchain.py", line 105, in front_middle_end
    refine(pm, ir, optimizations)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/middlend.py", line 61, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 236, in apply
    return a.apply(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 199, in apply
    new_node = self.run(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 187, in run
    n = super(Transformation, self).run(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 96, in run
    return self.visit(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 483, in generic_visit
    value = self.visit(value)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/optimizations/inlining.py", line 47, in visit_Stmt
    self.generic_visit(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 492, in generic_visit
    new_node = self.visit(old_value)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/passmanager.py", line 78, in visit
    return super(ContextManager, self).visit(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/ast.py", line 407, in visit
    return visitor(node)
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/pythran/optimizations/inlining.py", line 86, in visit_Call
    self.defs.append(ast.Assign(targets=[new_var],
  File "/Users/ljmartin/miniconda3/envs/compchem/lib/python3.9/site-packages/gast/gast.py", line 17, in create_node
    assert nbparam in (0, len(Fields)), \
AssertionError: Bad argument number for Assign: 3, expecting 2
```

**Comment by serge-sans-paille** [comment]
On Sun, Oct 09, 2022 at 04:21:54PM -0700, ljmartin wrote:
> Hi pythran, thank you for this project.
> 
> I'm having trouble compiling the [1]matrix multiplication example from the
> manual. Oddly, the dprod.py example prior to that works fine, so I believe the
> install is working (install was via mamba so I don't have a setup.py).
> 
> Do you have any idea what's leading to this error?
> Thanks!

It could be an obsolete version of gast is installed, can you give a try to:

    mamba install -U gast

Otherwise, I'll dig in...

Thanks for reporting!

**Comment by ljmartin** [comment]
Hi Serge, thanks for your comment. 
Thank you - the issue arose from using an older version of gast that was installed due to some complicated series of dependencies. I started a new env and it's fine now!
Thanks
Conflicts below in case it's useful:
```
(compchem) ljmartin@Lewiss-MacBook-Pro pdbe-molstar-example % pip install gast==0.5.3
Collecting gast==0.5.3
  Downloading gast-0.5.3-py3-none-any.whl (19 kB)
Installing collected packages: gast
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Successfully uninstalled gast-0.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.6.0 requires gast==0.4.0, but you have gast 0.5.3 which is incompatible.
tensorflow 2.6.0 requires numpy~=1.19.2, but you have numpy 1.22.4 which is incompatible.
tensorflow 2.6.0 requires wrapt~=1.12.1, but you have wrapt 1.13.3 which is incompatible.
pythran 0.9.12.post1 requires beniget~=0.4.0, but you have beniget 0.3.0 which is incompatible.
beniget 0.3.0 requires gast~=0.4.0, but you have gast 0.5.3 which is incompatible.
```
