### ISSUE TITLE
Why can't Windows 10 install pythran version 0.8.5

### ISSUE THREAD

**Issue by pipijiev12** [serge-sans-paille/pythran#2028]
Why can't Windows 10 install pythran version 0.8.5？
Collecting pythran==0.8.5
  Using cached http://mirrors.aliyun.com/pypi/packages/f0/68/fafbf561c3e6204040a5ee74811fd9858ac6e2e455ed2f3f7203a37a92d9/pythran-0.8.5.tar.gz (6.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      WARNING: The repository located at mirrors.aliyun.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS i
nstead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.aliyun.com'.
      ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
      ERROR: No matching distribution found for pytest-runner
      Traceback (most recent call last):
        File "D:\anaconda\envs\client_fusion\lib\site-packages\setuptools\installer.py", line 75, in fetch_build_egg
          subprocess.check_call(cmd)
        File "D:\anaconda\envs\client_fusion\lib\subprocess.py", line 363, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:\\anaconda\\envs\\client_fusion\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ppj\
\AppData\\Local\\Temp\\tmp526aks4q', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
     
      The above exception was the direct cause of the following exception:
     
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ppj\AppData\Local\Temp\pip-install-vh2dc5n7\pythran_f821525ed09948bdae90cda4c8fff119\setup.py", line 219, in <module>
          'develop': DevelopWithThirdParty})
        File "D:\anaconda\envs\client_fusion\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "D:\anaconda\envs\client_fusion\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "D:\anaconda\envs\client_fusion\lib\site-packages\setuptools\dist.py", line 809, in fetch_build_eggs
          replace_conflicting=True,
        File "D:\anaconda\envs\client_fusion\lib\site-packages\pkg_resources\__init__.py", line 768, in resolve
          replace_conflicting=replace_conflicting
        File "D:\anaconda\envs\client_fusion\lib\site-packages\pkg_resources\__init__.py", line 1051, in best_match
          return self.obtain(req, installer)
        File "D:\anaconda\envs\client_fusion\lib\site-packages\pkg_resources\__init__.py", line 1063, in obtain
          return installer(requirement)
        File "D:\anaconda\envs\client_fusion\lib\site-packages\setuptools\dist.py", line 877, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "D:\anaconda\envs\client_fusion\lib\site-packages\setuptools\installer.py", line 77, in fetch_build_egg
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['D:\\anaconda\\envs\\client_fusion\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\pp
j\\AppData\\Local\\Temp\\tmp526aks4q', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by serge-sans-paille** [comment]
Looks like a broken dependency on pytest-runner.

Current pythran version is 0.12, 0.8.5 is 4 years old, I unfortunately don't have time to support obsolete version.
