### ISSUE TITLE
Some tests still want numpy.distutils

### ISSUE THREAD

**Issue by musicinmybrain** [serge-sans-paille/pythran#2148]
Since `numpy` 1.26.0 removed `numpy.distutils` on Python 3.12, we are still seeing a few tests failing in Fedora Rawhide even with `pythran` 0.14.0, which includes https://github.com/serge-sans-paille/pythran/pull/2049.

```
=================================== FAILURES ===================================
___________________ TestDistutils.test_setup_bdist_install3 ____________________
[…]
E           subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'bdist', '--dist-dir=bdist']' ret
urned non-zero exit status 1.

/usr/lib64/python3.12/subprocess.py:413: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pythran-0.14.0/pythran/tests/test_distutils_numpy/setup.py", line 1, in <module>
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy.distutils'
_______________________ TestDistutils.test_setup_build3 ________________________
[…]
E           subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'build']' returned non-zero exit status 1.

/usr/lib64/python3.12/subprocess.py:413: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pythran-0.14.0/pythran/tests/test_distutils_numpy/setup.py", line 1, in <module>
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy.distutils'
___________________ TestDistutils.test_setup_sdist_install3 ____________________
[…]
E           subprocess.CalledProcessError: Command '['/usr/bin/python3', 'setup.py', 'sdist', '--dist-dir=sdist3']' returned non-zero exit status 1.

/usr/lib64/python3.12/subprocess.py:413: CalledProcessError
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/pythran-0.14.0/pythran/tests/test_distutils_numpy/setup.py", line 1, in <module>
    from numpy.distutils.core import setup
ModuleNotFoundError: No module named 'numpy.distutils'
```

Please consider skipping these tests when `numpy.distutils` is not available.

**Comment by serge-sans-paille** [comment]
#2149 fixes the issue - and tests it under py 3.12. That wasn't a breeze!

**Comment by musicinmybrain** [comment]
Thanks! That [seems to work](https://src.fedoraproject.org/rpms/pythran/pull-request/29) in Fedora Rawhide, too. (Well, the CI is still running, but it worked in local testing.)

**Comment by serge-sans-paille** [comment]
@rgommers this is touching `numpy.distutils`, I'd bve very happy of you could double check this change on scipy config?
