### ISSUE TITLE
complied with `np.zeros`  for matmulpy test

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#460]
hi, 
I tried `matmul.py` in `tests/cases/` folder and changed `list` to numpy array for two matrices. However, the `zeros` matrix will cause compiling error if using `numpy.zeros`; it's fine if using `list list`

Working code
```python
#pythran export matrix_multiply(float[][], float [][])
import numpy as np

def zero(n,m): return [[0 for row in xrange(n)] for col in xrange(m)]
def matrix_multiply(m0, m1):
    # new_matrix = np.zeros(len(m0),len(m1[0]))
    new_matrix = zero(len(m0),len(m1[0]))
    for i in xrange(len(m0)):
        for j in xrange(len(m1[0])):
            r=0
            "omp parallel for reduction(+:r)"
            for k in xrange(len(m1)):
                r += m0[i][k]*m1[k][j]
            new_matrix[i][j]=r
    return new_matrix
```

NOT working code: using `np.zeros`

Hai

**Comment by hainm** [comment]
Error
```python
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::ndarray<double, 2ul>; argument_type1 = pythonic::types::ndarray<double, 2ul>; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:315:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
               new_matrix[i][j] = r;
                            ^
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::ndarray<double, 2ul>; argument_type1 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:319:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; argument_type1 = pythonic::types::ndarray<double, 2ul>; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:323:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; argument_type1 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:327:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::ndarray<double, 2ul>; argument_type1 = pythonic::types::ndarray<double, 2ul>; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:315:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
               new_matrix[i][j] = r;
                            ^
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::ndarray<double, 2ul>; argument_type1 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:319:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; argument_type1 = pythonic::types::ndarray<double, 2ul>; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:323:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
/tmp/tmpEZDiQB.cpp: In instantiation of 'typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type __pythran_matmul::matrix_multiply::operator()(const argument_type0&, const argument_type1&) const [with argument_type0 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; argument_type1 = pythonic::types::numpy_texpr<pythonic::types::ndarray<double, 2ul> >; typename __pythran_matmul::matrix_multiply::type<argument_type0, argument_type1>::result_type = pythonic::types::ndarray<long int, 1ul>]':
/tmp/tmpEZDiQB.cpp:327:52:   required from here
/tmp/tmpEZDiQB.cpp:218:28: error: subscripted value is neither array nor pointer
CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!
E: ('error: Command "/mnt/raidc2/haichit/anaconda3/envs/pythran_python2/bin/g++-4.9 -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE_GMP -DENABLE_PYTHON_MODULE -I/mnt/raidc2/haichit/anaconda3/envs/pythran_python2/include -I/mnt/raidc2/haichit/anaconda3/envs/pythran_python2/lib/python2.7/site-packages/pythran -I/mnt/raidc2/haichit/anaconda3/envs/pythran_python2/lib/python2.7/site-packages/numpy/core/include -I/mnt/raidc2/haichit/anaconda3/envs/pythran_python2/include/python2.7 -c /tmp/tmpEZDiQB.cpp -o /tmp/tmptw9yvV/tmp/tmpEZDiQB.o -std=c++11 -fno-math-errno -w" failed with exit status 1',)
```

**Comment by pbrunet** [comment]
Hi,

This is a partially expected behavior.
Your error is normal because the `numpy.zeros` type for the first argument is "int or sequences of ints".
It means you should have a tuple value.

You should have better returned information but it will be part of the work to be done in the next year.

BTW, the error with CPython is : 
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    matrix_multiply([[1, 2], [3, 4]], [[5, 6], [7, 8]])
  File "test.py", line 6, in matrix_multiply
    new_matrix = np.zeros(len(m0),len(m1[0]))
TypeError: data type not understood

```

**Comment by hainm** [comment]
ah, sorry for the wrong syntax with numpy. should be 
```python
new_matrix = np.zeros((len(m0),len(m1[0])), dtype='f4')
```

**Comment by pbrunet** [comment]
Ok, In this case, you will certainly have an error too as we do not support "string dtype" for now. You should use `numpy.float` or `numpy.float32` here.

**Comment by serge-sans-paille** [comment]
On Wed, Jun 03, 2015 at 12:05:29AM -0700, pbrunet wrote:
> Ok, In this case, you will certainly have an error too as we do not support "string dtype" for now. You should use `numpy.float` or `numpy.float32` here.

@pbrunet : we could develop a pass that recognizes this particular
construct and turn it into a typed one. At least if the litteral is used
in the argument (after forward substitution and constant propagation).

**Comment by hainm** [comment]
@pbrunet thanks. with np.float, I can compile now.

Hai

**Comment by hainm** [comment]
I think problem is solved now. I should go ahead closing this issue.
