### ISSUE TITLE
AttributeError: Distribution instance has no attribute 'exclude_package_data'

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#489]
```bash
$ python ./setup.py install
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
running build
running build_py
Traceback (most recent call last):
  File "./setup.py", line 193, in <module>
    cmdclass={'build_py': BuildWithPly, 'test': PyTest})
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/build_py.py", line 77, in finalize_options
    self.exclude_package_data = self.distribution.exclude_package_data or {}
AttributeError: Distribution instance has no attribute 'exclude_package_data'

```

any idea how to fix this? just trying to `python setup.py install`

**Comment by serge-sans-paille** [comment]
> any idea how to fix this? just trying to `python setup.py install`

I need more info to reproduce : is this a raw install of anaconda?
which version of pythran are you using? (from the git? which SHA1?)

Thanks for the exhaustive testing, you're really helping us to build
better software :-)

**Comment by hainm** [comment]
> I need more info to reproduce : is this a raw install of anaconda?

What do you mean `raw install`? I created python2.7 environment for testing pythran (I am using py3)

$ which python
/mnt/raidc2/haichit/anaconda3/envs/py2/bin/python

> which version of pythran are you using? (from the git? which SHA1?)

```
$ git remote -v
origin  https://github.com/serge-sans-paille/pythran (fetch)
origin  https://github.com/serge-sans-paille/pythran (push)
hnguyen@x ~/programs/pythran (master) $ git pull origin master
From https://github.com/serge-sans-paille/pythran
 * branch            master     -> FETCH_HEAD
Already up-to-date.
```

then `python ./setup.py install`, I got above error.

> Thanks for the exhaustive testing, you're really helping us to build
better software :-)

No problem, I am just curious.

**Comment by hainm** [comment]
oops, this is the last commit

```
commit 2dc7bd98fa1900520e12f0feaf91cd3449e768c8
Merge: 8af46e5 dc3e037
Author: pbrunet <pierrick.brunet@telecom-bretagne.eu>
Date:   Sat Oct 10 21:50:26 2015 +0200

    Merge pull request #482 from serge-sans-paille/fix/numpy-gexpr-and-cie

    Fix/numpy gexpr and cie
```

**Comment by pbrunet** [comment]
I can't reproduce it here.

I suspect that some setuptools version ask for the `exclude_package_data`.
Can you test it with the branch : "setuptools_pkgdata"?

2015-10-11 10:10 GMT+02:00 Hai Nguyen <notifications@github.com>:

**Comment by hainm** [comment]
@pbrunet 

here is the full error after I checked out that branch

```bash
$ git pull origin setuptools_pkgdata
From https://github.com/serge-sans-paille/pythran
 * branch            setuptools_pkgdata -> FETCH_HEAD
Already up-to-date.
(py2)hnguyen@bell ~/programs/pythran (setuptools_pkgdata) $ python ./setup.py install
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'exclude_package_data'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running install
running build
running build_py
Traceback (most recent call last):
  File "./setup.py", line 196, in <module>
    cmdclass={'build_py': BuildWithPly, 'test': PyTest})
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/command/install.py", line 563, in run
    self.run_command('build')
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/site-packages/setuptools/command/build_py.py", line 77, in finalize_options
    self.exclude_package_data = self.distribution.exclude_package_data or {}
AttributeError: Distribution instance has no attribute 'exclude_package_data'
``

**Comment by pbrunet** [comment]
It looks to be a problem with setuptools as it raise a lot of warning for
unknown attributs. Can you check your setuptools versions?

Here :
`python -c "import setuptools; print setuptools.__version__"`
18.2


2015-10-11 20:25 GMT+02:00 Hai Nguyen <notifications@github.com>:

**Comment by hainm** [comment]
oh, not sure why my version is 0.6 (although I use conda to update it). 

```bash
$ python -c "import setuptools; print setuptools.__version__"
0.6
```

Just tried to use `pip` to install 18.2 version. No error any more but got one with NT2. Will try install new one and report later.

Can you add version requirement for pythran?

**Comment by serge-sans-paille** [comment]
@hainm : the only solution I see is something like adding :+1: 

```python
import setuptools
if setuptools.__version__ < ...:
    raise ImportError(...)
```

Does that seem suitable to you?

**Comment by hainm** [comment]
Yeah

Hai

**Comment by serge-sans-paille** [comment]
@hainm can you check #508 correctly detects your issue?

**Comment by hainm** [comment]
Hi

Since I got the error, I upgraded my setuptools, not sure how to test it. Downgrade? 

Hai

**Comment by hainm** [comment]
anyway, I just downgraded to setuptools 10.0 and got 

```python

********************************************
* Setuptools must be at least version 18.2 *
********************************************

Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    raise ImportError("setuptools")
ImportError: setuptools
```

plus after upgrading setuptools, I did not get error in my 1st post.

**Comment by jcfr** [comment]
> AttributeError: Distribution instance has no attribute 'exclude_package_data'

Having faced this issue in a different context, the issue was most likely caused by the fact the installation of `setuptools` was done from its source tree available on https://github.com/pypa/setuptools and was **NOT** `bootstrapped` before being installed.

Not that installing using the source distribution available on pypi does not have problem.

To bootstrap before install, the following can be done:

```
cd setuptools
python bootstrap.py
python setup.py install
```

or if you prefer a non zipped version

```
cd setuptools
python bootstrap.py
python setup.py easy_install --always-unzip .
```

Omitting to bootstrap will prevent the file `entry_points.txt` for egg (or `metadata.json` for wheel) from being installed.

Without that file, the following code found in [setuptools/dist.py#L319-L320@d8e1ed5](https://github.com/pypa/setuptools/blob/d8e1ed570126dfc99ed7f9126df3bfc890e7005d/setuptools/dist.py#L319-L320) wouldn't extend distribution object with the setuptools specific keywords:

```python
class Distribution(Distribution_parse_config_files, _Distribution):
    [...]
    def __init__(self, attrs=None):
        [...]
        for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
            vars(self).setdefault(ep.name, None)
        [...]
```
