### ISSUE TITLE
pythran.conversion.ConversionError 

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#619]
Hello,
I have this very strange bug::  

    $ pip install pythran -U
    Requirement already up-to-date: pythran in /tmp/venv_ble_test/lib/python2.7/site-packages
    Requirement already up-to-date: ply>=3.4 in /tmp/venv_ble_test/lib/python2.7/site-packages (from pythran)
    Requirement already up-to-date: networkx>=1.5 in /tmp/venv_ble_test/lib/python2.7/site-packages (from pythran)
    Requirement already up-to-date: decorator in /tmp/venv_ble_test/lib/python2.7/site-packages (from pythran)
    $
    $ python -c "from pythran import cxxtypes"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/__init__.py", line 39, in <module>
        from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/toolchain.py", line 6, in <module>
        from pythran.backend import Cxx
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/backend.py", line 8, in <module>
        from pythran.analyses import ArgumentEffects, BoundExpressions, Dependencies
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/analyses/__init__.py", line 12, in <module>
        from .aliases import Aliases, StrictAliases
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/analyses/aliases.py", line 6, in <module>
        from pythran.syntax import PythranSyntaxError
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/syntax.py", line 7, in <module>
        from pythran.tables import MODULES
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/tables.py", line 951, in <module>
        save_arguments((), MODULES)
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/tables.py", line 936, in save_arguments
        save_arguments(module_name + (elem,), signature)
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/tables.py", line 947, in save_arguments
        signature.args.defaults = map(to_ast, spec.defaults)
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/conversion.py", line 112, in to_ast
        raise ConversionError()
    pythran.conversion.ConversionError
    $

**Comment by LuisBL** [comment]
The result of pip freeze:: 

    ansicolors==1.0.2
    blist==1.3.6
    colorlog==2.7.0
    cycler==0.10.0
    Cython==0.25.1
    decorator==4.0.10
    liac-arff==2.1.0
    matplotlib==1.5.3
    networkx==1.11
    numexpr==2.6.1
    numpy==1.11.2
    pager==3.3
    pandas==0.18.1
    pexpect==4.2.1
    pkg-resources==0.0.0
    ply==3.9
    prettytable==0.7.2
    protobuf==3.1.0.post1
    psutil==4.4.2
    ptyprocess==0.5.1
    pyparsing==2.1.10
    python-dateutil==2.5.3
    pythran==0.7.6.post1
    pytz==2016.7
    PyYAML==3.12
    rpy2==2.8.3
    scikit-learn==0.18
    scipy==0.18.1
    seaborn==0.7.1
    setuptools-git==1.2.dev0
    setuptools-scm==1.15.0
    sharedmem==0.3.5
    singledispatch==3.4.0.3
    six==1.10.0
    tables==3.3.0
    termcolor==1.1.0

**Comment by LuisBL** [comment]
pip and setuptools version::

    (venv_ble_test) luis@spinoza:~/lab/sandbox/ble$ pip --version
    pip 9.0.0 from /tmp/venv_ble_test/local/lib/python2.7/site-packages (python 2.7)
    (venv_ble_test) luis@spinoza:~/lab/sandbox/ble$ python -m easy_install --version
    setuptools 28.8.0 from /tmp/venv_ble_test/lib/python2.7/site-packages (Python 2.7)
    (venv_ble_test) luis@spinoza:~/lab/sandbox/ble$

**Comment by LuisBL** [comment]
The same with pip 8.1 and setuptools 20.7::

    $ pip --version
    pip 8.1.2 from /tmp/venv_ble_test/local/lib/python2.7/site-packages (python 2.7)
    $
    (venv_ble_test) luis@spinoza:/tmp/venv_ble_test$ python -m easy_install --version
    setuptools 20.7.0 from /tmp/venv_ble_test/lib/python2.7/site-packages (Python 2.7)
    $
    $ python -c "from pythran.tables import MODULES"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/__init__.py", line 39, in <module>
        from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/toolchain.py", line 6, in <module>
        from pythran.backend import Cxx
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/backend.py", line 8, in <module>
        from pythran.analyses import ArgumentEffects, BoundExpressions, Dependencies
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/analyses/__init__.py", line 12, in <module>
        from .aliases import Aliases, StrictAliases
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/analyses/aliases.py", line 6, in <module>
        from pythran.syntax import PythranSyntaxError
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/syntax.py", line 7, in <module>
        from pythran.tables import MODULES
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/tables.py", line 951, in <module>
        save_arguments((), MODULES)
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/tables.py", line 936, in save_arguments
        save_arguments(module_name + (elem,), signature)
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/tables.py", line 947, in save_arguments
        signature.args.defaults = map(to_ast, spec.defaults)
      File "/tmp/venv_ble_test/local/lib/python2.7/site-packages/pythran/conversion.py", line 112, in to_ast
        raise ConversionError()
    pythran.conversion.ConversionError
    $

**Comment by serge-sans-paille** [comment]
Thanks for the bugreport! That's indeed very strange... I'll investigate :-)

**Comment by LuisBL** [comment]
It's strange I get this when I create a fresh virutualenv and install all on it. I do not get the error on my old virtualenv where I'm use to work.
If I can provide any kind of help, ...

**Comment by LuisBL** [comment]
it's in numpy==1.11.2

pythran/conversion.py
   def to_ast(value):
    with value ==   numpy._globals._NoValue

**Comment by LuisBL** [comment]
I confirm we do not get this bug with::
  
    numpy==1.11.0
