### ISSUE TITLE
New dependency not included in setup.py: gast

### ISSUE THREAD

**Issue by ashwinvis** [serge-sans-paille/pythran#625]
I installed pythran via [ArchLinux AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-pythran-git)

However I get the following error after installationpython2 -c 'import pythran'
Traceback (most recent call last):             
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pythran/__init__.py", line 39, in <module>
    from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
  File "/usr/lib/python2.7/site-packages/pythran/toolchain.py", line 6, in <module>
    from pythran.backend import Cxx
  File "/usr/lib/python2.7/site-packages/pythran/backend.py", line 8, in <module>
    from pythran.analyses import ArgumentEffects, BoundExpressions, Dependencies
  File "/usr/lib/python2.7/site-packages/pythran/analyses/__init__.py", line 12, in <module>
    from .aliases import Aliases, StrictAliases
  File "/usr/lib/python2.7/site-packages/pythran/analyses/aliases.py", line 3, in <module>
    from pythran.analyses.global_declarations import GlobalDeclarations
  File "/usr/lib/python2.7/site-packages/pythran/analyses/global_declarations.py", line 3, in <module>
    from pythran.passmanager import ModuleAnalysis
  File "/usr/lib/python2.7/site-packages/pythran/passmanager.py", line 14, in <module>
    import gast as ast
ImportError: No module named gast

`$ 
`

**Comment by serge-sans-paille** [comment]
That's probably a packaging issue from AUR, gast is correctly listed in the [requirements.txt](https://github.com/serge-sans-paille/pythran/blob/master/requirements.txt) file

**Comment by serge-sans-paille** [comment]
I confirm, the package is broken, cf https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-pythran-git#n9

**Comment by serge-sans-paille** [comment]
@xantares : you seem to be the original maintainer of the AUR port, could you add ``gast`` and ``six`` to the requirements?

**Comment by ashwinvis** [comment]
Yes, it was just an AUR issue. Apologies! And thanks to @xantares for fixing it promptly.

However, I don't understand why the requirements.txt is not parsed while running via AUR PKGBUILD. Can someone shed light on this?
