### ISSUE TITLE
python 3.6 Pb request "getfullargspec() API "

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#653]
I have a gitlab-ci.yml calling pythran compilation, it work well with python 3.5
If I use **python3.6** I get this traceback::

```
$ make clean psi test
pyc, logs, ftest, dist, build ... Cleaned
/tmp/ftest_from_wheels
/tmp/venv_ble_test
Obtaining file:///builds/r_d/ble
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/builds/r_d/ble/setup.py", line 19, in <module>
        from pythran.dist import PythranExtension
      File "/usr/local/lib/python3.6/site-packages/pythran/__init__.py", line 39, in <module>
        from pythran.toolchain import (generate_cxx, compile_cxxfile, compile_cxxcode,
      File "/usr/local/lib/python3.6/site-packages/pythran/toolchain.py", line 6, in <module>
        from pythran.backend import Cxx
      File "/usr/local/lib/python3.6/site-packages/pythran/backend.py", line 8, in <module>
        from pythran.analyses import ArgumentEffects, BoundExpressions, Dependencies
      File "/usr/local/lib/python3.6/site-packages/pythran/analyses/__init__.py", line 12, in <module>
        from .aliases import Aliases, StrictAliases
      File "/usr/local/lib/python3.6/site-packages/pythran/analyses/aliases.py", line 6, in <module>
        from pythran.syntax import PythranSyntaxError
      File "/usr/local/lib/python3.6/site-packages/pythran/syntax.py", line 7, in <module>
        from pythran.tables import MODULES
      File "/usr/local/lib/python3.6/site-packages/pythran/tables.py", line 4403, in <module>
        save_arguments((), MODULES)
      File "/usr/local/lib/python3.6/site-packages/pythran/tables.py", line 4379, in save_arguments
        save_arguments(module_name + (elem,), signature)
      File "/usr/local/lib/python3.6/site-packages/pythran/tables.py", line 4385, in save_arguments
        spec = inspect.getargspec(obj)
      File "/usr/local/lib/python3.6/inspect.py", line 1045, in getargspec
        raise ValueError("Function has keyword-only parameters or annotations"
    ValueError: Function has keyword-only parameters or annotations, use getfullargspec() API which can support them
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /builds/r_d/ble/
make: *** [psi] Error 1
```

**Comment by serge-sans-paille** [comment]
I never tested pythran under python 3.6. Will do :-)

**Comment by serge-sans-paille** [comment]
@LuisBL can you provide a simpler way to reproduce ? Something like a minimal setup.py ? All tests are ok using python 3.6.0 here.

**Comment by serge-sans-paille** [comment]
(maybe the minor 3.6 version differs ?)

**Comment by serge-sans-paille** [comment]
I'm interested in your numpy version too btw.

**Comment by serge-sans-paille** [comment]
@LuisBL I cannot reproduce. I need the exact version information ;-)

**Comment by ttylec** [comment]
@serge-sans-paille same error on OSX with 3.6.1

**Comment by serge-sans-paille** [comment]
Thanks @ttylec I now have a reproducer!

**Comment by serge-sans-paille** [comment]
@ttylec @LuisBL can you confirm #667 fixes your issue?

**Comment by LuisBL** [comment]
@serge-sans-paille you patch fix the issue (docker image python3.6) thank you.
