### ISSUE TITLE
ImportError: No module named scipy

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#772]
Since becf7cf677cbd3bbe81c862051f098baad79acdd, I now have the following error (my code has nothing related to scipy):
```
WARNING: Disabling color, you really want to install colorlog.
WARNING: Pythran support disabled for module: scipy.special
Traceback (most recent call last):
  File "/home/saxs/virtual_envs/cosmic/bin/pythran", line 11, in <module>
    load_entry_point('pythran==0.8.3', 'console_scripts', 'pythran')()
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/run.py", line 141, in run
    **compile_flags(args))
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/toolchain.py", line 432, in compile_pythranfile
    **kwargs)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/toolchain.py", line 364, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/toolchain.py", line 138, in generate_cxx
    refine(pm, ir, optimizations)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/middlend.py", line 49, in refine
    apply_optimisation |= pm.apply(optimization, node)[0]
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/passmanager.py", line 216, in apply
    res = a.apply(node, ctx)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/passmanager.py", line 178, in apply
    new_node = self.run(node, ctx)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/passmanager.py", line 171, in run
    n = super(Transformation, self).run(node, ctx)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/passmanager.py", line 113, in run
    self.prepare(node, ctx)
  File "/home/saxs/virtual_envs/cosmic/local/lib/python2.7/site-packages/pythran-0.8.3-py2.7.egg/pythran/optimizations/constant_folding.py", line 49, in prepare
    self.env[alias_module_name] = __import__(import_name)
ImportError: No module named scipy
```

**Comment by serge-sans-paille** [comment]
mmmh, do you have ``scipy`` installed ? there's no reason you should have it, juste to make you sure you don't.

**Comment by diorcety** [comment]
No i'm in a virtualenv without scipy

**Comment by serge-sans-paille** [comment]
Does #773 fix your issue?

**Comment by diorcety** [comment]
Yes it does
