### ISSUE TITLE
np.bitwise_xor.reduce gives error

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#844]
This line:

            if np.bitwise_xor.reduce([x[b] for b in Bits[i]]) != 0:

gives:
Traceback (most recent call last):
  File "/home/nbecker/.local/bin/pythran", line 11, in <module>
    load_entry_point('pythran==0.8.4.post0', 'console_scripts', 'pythran')()
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/run.py", line 150, in run
    **compile_flags(args))
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/toolchain.py", line 464, in compile_pythranfile
    **kwargs)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/toolchain.py", line 396, in compile_pythrancode
    module, error_checker = generate_cxx(module_name, pythrancode, specs, opts)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/toolchain.py", line 158, in generate_cxx
    optimizations)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/toolchain.py", line 128, in front_middle_end
    refine(pm, ir, optimizations)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/middlend.py", line 33, in refine
    pm.gather(ExtendedSyntaxCheck, node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 196, in gather
    return a.run(node, ctx)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 130, in run
    super(Analysis, self).run(node, ctx)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 113, in run
    self.prepare(node, ctx)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 104, in prepare
    result = d.run(rnode, ctx)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 130, in run
    super(Analysis, self).run(node, ctx)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 114, in run
    return self.visit(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/usr/lib64/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 543, in visit_FunctionDef
    self.generic_visit(node)
  File "/usr/lib64/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 683, in visit_While
    self.generic_visit(node)
  File "/usr/lib64/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 660, in visit_For
    self.generic_visit(node)
  File "/usr/lib64/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 707, in visit_If
    self.visit(node.test)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 156, in visit_UnaryOp
    self.generic_visit(node)
  File "/usr/lib64/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 351, in visit_Call
    self.generic_visit(node)
  File "/usr/lib64/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/passmanager.py", line 80, in visit
    return super(ContextManager, self).visit(node)
  File "/usr/lib64/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 380, in visit_Attribute
    return self.add(node, {Aliases.access_path(node)})
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/analyses/aliases.py", line 109, in access_path
    return Aliases.access_path(node.value)[demangle(node.attr)]
  File "/home/nbecker/.local/lib/python3.6/site-packages/pythran-0.8.4.post0-py3.6.egg/pythran/intrinsic.py", line 224, in __getitem__
    return self.fields[key]
KeyError: 'reduce'
scons: *** [G] Error 1

**Comment by serge-sans-paille** [comment]
I though we were supporting that. I'll check as soon as possible, which does not mean today :-)

**Comment by serge-sans-paille** [comment]
ok, we're actually supporting accumulate, but not reduce...

**Comment by serge-sans-paille** [comment]
Something like two years later, should be fixed by #1549 

Once again, patience shall prevail :-)
