### ISSUE TITLE
setting for python library

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#889]
To build on pypy, I need to link to libpypy3-c.so, which is installed in a strange location.  I need a way to specify this to the link step.

**Comment by nbecker** [comment]
My report is incorrect, the problem is not linking to libpypy3-c.so.
I'm trying to debug a segfault:
(gdb) where
#0  0x00007fffd7440088 in (anonymous namespace)::pythonic::from_python<(anonymous namespace)::pythonic::types::list<(anonymous namespace)::pythonic::types::list<long> > >::convert(_object*) () from /home/nbecker/pypy3-env/site-packages/scma-ofdm-nr/G.pypy3-60-x86_64-linux-gnu.so
#1  0x00007fffd7445fab in __pythran_wrap_Decoding_logBP2(_object*, _object*, _object*) [clone .isra.918] ()
   from /home/nbecker/pypy3-env/site-packages/scma-ofdm-nr/G.pypy3-60-x86_64-linux-gnu.so
#2  0x00007fffd7449ba8 in __pythran_wrapall_Decoding_logBP(_object*, _object*, _object*) ()
   from /home/nbecker/pypy3-env/site-packages/scma-ofdm-nr/G.pypy3-60-x86_64-linux-gnu.so
#3  0x00007ffff5d6c853 in ?? () from /home/nbecker/pypy3-env/bin/libpypy3-c.so

**Comment by serge-sans-paille** [comment]
That looks like an issue at the C-APi level. Don't know if it commes
from pythran or Pypy though.

To help you in your debug, add that to you ~/.pythranrc

```
[compiler]
ldflags=-Wl,-O1
```

This avoids the stripping step

**Comment by serge-sans-paille** [comment]
@nbecker can you provide the .py to reproduce the error?

**Comment by serge-sans-paille** [comment]
ok, that's you're usual test case, I'll try to reproduce
